service:
  name: fullstack-blog

plugins:
  - '@hewmen/serverless-plugin-typescript'
  - serverless-tscpaths
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-plugin-warmup

custom:
  # Enable warmup on all functions (only for production and staging)
  warmup:
    enabled: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: ap-southeast-1

functions:
  index: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    handler: src/lambda.handler
    events:
      - http:
          cors: true
          path: '/'
          method: any
